version: '3'
services:
  mysql:
    image: mysql:8
    container_name: shinhan_pda1_final_project
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shinhanPDA1
