version: '3'
services:
  mysql:
    image: mysql:8
    container_name: pda1_project
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shinhanPDA1
  mysql2:
    image: mysql:8
    container_name: pda1_information_connector
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infoConnector
