spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/shinhanPDA1?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000

jwt:
  secret: '62ee24aa5950496692f0c633e26b58b062ee24aa5950496692f0c633e26b58b0'


server:
  port: 8081

